# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
    ecm: pay-justice/export-commit-message@0.0.1
workflows:
    my-workflow:
        jobs:
            - export_git_commit_message
            - build:
                  context:
                      - PCLOUD
                  filters:
                      branches:
                          only:
                              - master
                              - circleci
                              - /feature.*/
jobs:
    build:
        docker:
            # specify the version you desire here
            - image: circleci/openjdk:11-browsers-legacy

            # Specify service dependencies here if necessary
            # CircleCI maintains a library of pre-built images
            # documented at https://circleci.com/docs/2.0/circleci-images/
            # - image: circleci/postgres:9.4

        working_directory: ~/repo

        environment:
            # Customize the JVM maximum heap limit
            MAVEN_OPTS: -Xmx3200m

        steps:
            - checkout
            - ecm/export_commit

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "pom.xml" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: mvn dependency:go-offline

            - save_cache:
                  paths:
                      - ~/.m2
                  key: v1-dependencies-{{ checksum "pom.xml" }}

            - run: echo "build job, commit message >> ${env.GIT_COMMIT_MESSAGE}"
            - run: git config user.email "n.karakin@qmul.ac.uk"
            - run: git config user.name "Via CircleCI Build at gihubme"
            # run tests!
            - run: mvn --batch-mode release:prepare release:perform -s .circleci/settings.xml

